# pybind config
RENDER_RATE = 1
CAPTURE_RATE = 1
VIEW_RATE = 1
MAX_FPS = 10000000
MAX_UPS = 10000000

# Game config
AUTO_ATTACK = False
AUTO_HARVEST = True

# Player config
HISTORY_SIZE = 10  # Number of actions to store

# Action ids
ATTACK_CLOSEST_TARGET = 1
HARVEST_CLOSEST_RESOURCE = 2
RANDOM_MOVE = 3
NO_ACTION = 4
